### Regression Model In Keras Part D

First, the appropriate libraries are imported, i.e. Pandas and NumPy.

In [1]:
import pandas as pd #This code imports pandas libraries
import numpy as np #This code imports NumPy libraries

Next, we load the csv file using the pandas library into a dataframe.

In [2]:
c_data = pd.read_csv('https://cocl.us/concrete_data') #This code reads the data from the csv file into a pandas dataframe
c_data.head() #We then display the first 5 rows of data

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30

We then check the shape of the dataframe.

In [3]:
c_data.shape

(1030, 9)


we determine if the data is erroneous.

In [4]:
c_data.describe()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
count,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000
mean,281.167864,73.895825,54.188350,181.567282,6.204660,972.918932,773.580485,45.662136,35.817961
std,104.506364,86.279342,63.997004,21.354219,5.973841,77.753954,80.175980,63.169912,16.705742
min,102.000000,0.000000,0.000000,121.800000,0.000000,801.000000,594.000000,1.000000,2.330000
25%,192.375000,0.000000,0.000000,164.900000,0.000000,932.000000,730.950000,7.000000,23.710000
50%,272.900000,22.000000,0.000000,185.000000,6.400000,968.000000,779.500000,28.000000,34.445000
75%,350.000000,142.950000,118.300000,192.000000,10.200000,1029.400000,824.000000,56.000000,46.135000
max,540.000000,359.400000,200.100000,247.000000,32.200000,1145.000000,992.600000,365.000000,82.600000

In [5]:
c_data.isnull().sum()

Cement                0
Blast Furnace Slag    0
Fly Ash               0
Water                 0
Superplasticizer      0
Coarse Aggregate      0
Fine Aggregate        0
Age                   0
Strength              0
dtype: int64

From this, we can see that the column 'Strength' is dependent on the values on the other columns. Therefore we split the dataframe into two: the target (strength)
and the predictors (the other columns).

In [6]:
c_data_columns = c_data.columns
predictors = c_data[c_data_columns[c_data_columns != 'Strength']] # creates pandas dataframe for all columns except Strength
target = c_data['Strength'] # Strength column in the data frame
predictors.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360

We can then see the first 5 values of the predictor

In [7]:
target.head()

0    79.99
1    61.89
2    40.27
3    41.05
4    44.30
Name: Strength, dtype: float64

## Normalize the data
We subtract the mean of the predictors from the predictors and divide by the standard deviation.

In [8]:
predictors = (predictors-predictors.mean())/predictors.std()
predictors.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,0.862735,-1.217079,-0.279597
1,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,1.055651,-1.217079,-0.279597
2,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,3.551340
3,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,5.055221
4,-0.790075,0.678079,-0.846733,0.488555,-1.038638,0.070492,0.647569,4.976069

Additionally, we must save the number of predictors in such a manner as it is necessitated by the following function.

In [9]:
n_cols = predictors.shape[1] # number of predictors

Next We import Keras and all the requisite packages.

In [10]:
import keras
from keras.models import Sequential
from keras.layers import Dense

## Regression Model

We then make our regression model

In [11]:
# define regression model
def regression_model():
    # create model
    model = Sequential()#Creates a sequnetial model
    model.add(Dense(10, activation='relu', input_shape=(n_cols,)))# creates 10 nodes using the Relu function as an activation function
    model.add(Dense(10, activation='relu'))# adds hidden layer 1
    model.add(Dense(10, activation='relu'))#adds hidden layer 2
    model.add(Dense(1)) #The output layer
    
    # compile model
    model.compile(optimizer='adam', loss='mean_squared_error') #The optimizer used was adam and mean squared error is used as the loss in back propagation.
    return model

## Training and Testing
We now implement a test/train split to first train the data then test it.

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(predictors,  target, test_size=0.3, random_state = 4)

The model is then called and trained for 100 epochs.

In [13]:
R_model = regression_model()
R_model.fit(X_train, y_train, epochs=100, verbose=2)

Epoch 1/100
23/23 - 1s - loss: 1533.8357 - 647ms/epoch - 28ms/step
Epoch 2/100
23/23 - 0s - loss: 1493.0453 - 25ms/epoch - 1ms/step
Epoch 3/100
23/23 - 0s - loss: 1434.9440 - 32ms/epoch - 1ms/step
Epoch 4/100
23/23 - 0s - loss: 1347.1616 - 33ms/epoch - 1ms/step
Epoch 5/100
23/23 - 0s - loss: 1222.3928 - 31ms/epoch - 1ms/step
Epoch 6/100
23/23 - 0s - loss: 1056.1344 - 32ms/epoch - 1ms/step
Epoch 7/100
23/23 - 0s - loss: 853.3052 - 36ms/epoch - 2ms/step
Epoch 8/100
23/23 - 0s - loss: 633.6793 - 33ms/epoch - 1ms/step
Epoch 9/100
23/23 - 0s - loss: 451.0978 - 32ms/epoch - 1ms/step
Epoch 10/100
23/23 - 0s - loss: 334.2604 - 42ms/epoch - 2ms/step
Epoch 11/100
23/23 - 0s - loss: 277.8127 - 43ms/epoch - 2ms/step
Epoch 12/100
23/23 - 0s - loss: 248.2977 - 32ms/epoch - 1ms/step
Epoch 13/100
23/23 - 0s - loss: 228.9067 - 24ms/epoch - 1ms/step
Epoch 14/100
23/23 - 0s - loss: 215.0102 - 29ms/epoch - 1ms/step
Epoch 15/100
23/23 - 0s - loss: 204.4939 - 25ms/epoch - 1ms/step
Epoch 16/100
23/23 - 0s - loss: 195.6983 - 24ms/epoch - 1ms/step
Epoch 17/100
23/23 - 0s - loss: 189.2914 - 31ms/epoch - 1ms/step
Epoch 18/100
23/23 - 0s - loss: 183.5947 - 27ms/epoch - 1ms/step
Epoch 19/100
23/23 - 0s - loss: 178.3008 - 31ms/epoch - 1ms/step
Epoch 20/100
23/23 - 0s - loss: 173.8797 - 36ms/epoch - 2ms/step
Epoch 21/100
23/23 - 0s - loss: 169.5346 - 29ms/epoch - 1ms/step
Epoch 22/100
23/23 - 0s - loss: 165.6123 - 32ms/epoch - 1ms/step
Epoch 23/100
23/23 - 0s - loss: 162.4027 - 32ms/epoch - 1ms/step
Epoch 24/100
23/23 - 0s - loss: 159.2133 - 28ms/epoch - 1ms/step
Epoch 25/100
23/23 - 0s - loss: 156.3253 - 29ms/epoch - 1ms/step
Epoch 26/100
23/23 - 0s - loss: 153.5676 - 32ms/epoch - 1ms/step
Epoch 27/100
23/23 - 0s - loss: 150.9422 - 30ms/epoch - 1ms/step
Epoch 28/100
23/23 - 0s - loss: 148.3997 - 28ms/epoch - 1ms/step
Epoch 29/100
23/23 - 0s - loss: 146.3836 - 30ms/epoch - 1ms/step
Epoch 30/100
23/23 - 0s - loss: 144.6989 - 31ms/epoch - 1ms/step
Epoch 31/100
23/23 - 0s - loss: 142.8940 - 32ms/epoch - 1ms/step
Epoch 32/100
23/23 - 0s - loss: 140.7900 - 30ms/epoch - 1ms/step
Epoch 33/100
23/23 - 0s - loss: 138.8895 - 27ms/epoch - 1ms/step
Epoch 34/100
23/23 - 0s - loss: 137.2123 - 35ms/epoch - 2ms/step
Epoch 35/100
23/23 - 0s - loss: 135.6410 - 26ms/epoch - 1ms/step
Epoch 36/100
23/23 - 0s - loss: 134.0343 - 33ms/epoch - 1ms/step
Epoch 37/100
23/23 - 0s - loss: 132.2312 - 26ms/epoch - 1ms/step
Epoch 38/100
23/23 - 0s - loss: 130.9221 - 32ms/epoch - 1ms/step
Epoch 39/100
23/23 - 0s - loss: 129.3216 - 34ms/epoch - 1ms/step
Epoch 40/100
23/23 - 0s - loss: 127.6469 - 28ms/epoch - 1ms/step
Epoch 41/100
23/23 - 0s - loss: 126.2987 - 32ms/epoch - 1ms/step
Epoch 42/100
23/23 - 0s - loss: 125.0822 - 31ms/epoch - 1ms/step
Epoch 43/100
23/23 - 0s - loss: 123.7392 - 31ms/epoch - 1ms/step
Epoch 44/100
23/23 - 0s - loss: 122.5045 - 35ms/epoch - 2ms/step
Epoch 45/100
23/23 - 0s - loss: 121.1240 - 30ms/epoch - 1ms/step
Epoch 46/100
23/23 - 0s - loss: 120.1554 - 33ms/epoch - 1ms/step
Epoch 47/100
23/23 - 0s - loss: 118.9326 - 28ms/epoch - 1ms/step
Epoch 48/100
23/23 - 0s - loss: 117.9135 - 33ms/epoch - 1ms/step
Epoch 49/100
23/23 - 0s - loss: 116.7777 - 38ms/epoch - 2ms/step
Epoch 50/100
23/23 - 0s - loss: 115.8140 - 29ms/epoch - 1ms/step
Epoch 51/100
23/23 - 0s - loss: 115.7525 - 34ms/epoch - 1ms/step
Epoch 52/100
23/23 - 0s - loss: 114.3134 - 25ms/epoch - 1ms/step
Epoch 53/100
23/23 - 0s - loss: 112.8001 - 33ms/epoch - 1ms/step
Epoch 54/100
23/23 - 0s - loss: 111.8990 - 32ms/epoch - 1ms/step
Epoch 55/100
23/23 - 0s - loss: 110.9054 - 33ms/epoch - 1ms/step
Epoch 56/100
23/23 - 0s - loss: 110.1489 - 32ms/epoch - 1ms/step
Epoch 57/100
23/23 - 0s - loss: 109.2337 - 27ms/epoch - 1ms/step
Epoch 58/100
23/23 - 0s - loss: 107.9069 - 30ms/epoch - 1ms/step
Epoch 59/100
23/23 - 0s - loss: 107.1806 - 32ms/epoch - 1ms/step
Epoch 60/100
23/23 - 0s - loss: 105.9194 - 32ms/epoch - 1ms/step
Epoch 61/100
23/23 - 0s - loss: 105.2974 - 30ms/epoch - 1ms/step
Epoch 62/100
23/23 - 0s - loss: 104.2066 - 32ms/epoch - 1ms/step
Epoch 63/100
23/23 - 0s - loss: 103.7674 - 34ms/epoch - 1ms/step
Epoch 64/100
23/23 - 0s - loss: 102.5132 - 31ms/epoch - 1ms/step
Epoch 65/100
23/23 - 0s - loss: 101.3773 - 30ms/epoch - 1ms/step
Epoch 66/100
23/23 - 0s - loss: 100.7875 - 30ms/epoch - 1ms/step
Epoch 67/100
23/23 - 0s - loss: 99.6823 - 33ms/epoch - 1ms/step
Epoch 68/100
23/23 - 0s - loss: 98.9391 - 29ms/epoch - 1ms/step
Epoch 69/100
23/23 - 0s - loss: 97.8673 - 27ms/epoch - 1ms/step
Epoch 70/100
23/23 - 0s - loss: 97.3353 - 31ms/epoch - 1ms/step
Epoch 71/100
23/23 - 0s - loss: 96.1664 - 30ms/epoch - 1ms/step
Epoch 72/100
23/23 - 0s - loss: 95.4983 - 32ms/epoch - 1ms/step
Epoch 73/100
23/23 - 0s - loss: 94.3937 - 28ms/epoch - 1ms/step
Epoch 74/100
23/23 - 0s - loss: 93.8382 - 29ms/epoch - 1ms/step
Epoch 75/100
23/23 - 0s - loss: 93.6851 - 35ms/epoch - 2ms/step
Epoch 76/100
23/23 - 0s - loss: 91.4607 - 30ms/epoch - 1ms/step
Epoch 77/100
23/23 - 0s - loss: 91.0289 - 26ms/epoch - 1ms/step
Epoch 78/100
23/23 - 0s - loss: 90.1759 - 29ms/epoch - 1ms/step
Epoch 79/100
23/23 - 0s - loss: 89.0927 - 28ms/epoch - 1ms/step
Epoch 80/100
23/23 - 0s - loss: 88.6290 - 24ms/epoch - 1ms/step
Epoch 81/100
23/23 - 0s - loss: 87.8105 - 25ms/epoch - 1ms/step
Epoch 82/100
23/23 - 0s - loss: 86.8229 - 29ms/epoch - 1ms/step
Epoch 83/100
23/23 - 0s - loss: 86.0806 - 28ms/epoch - 1ms/step
Epoch 84/100
23/23 - 0s - loss: 85.2405 - 28ms/epoch - 1ms/step
Epoch 85/100
23/23 - 0s - loss: 84.4929 - 29ms/epoch - 1ms/step
Epoch 86/100
23/23 - 0s - loss: 83.5372 - 28ms/epoch - 1ms/step
Epoch 87/100
23/23 - 0s - loss: 82.7627 - 28ms/epoch - 1ms/step
Epoch 88/100
23/23 - 0s - loss: 82.0415 - 28ms/epoch - 1ms/step
Epoch 89/100
23/23 - 0s - loss: 81.4481 - 32ms/epoch - 1ms/step
Epoch 90/100
23/23 - 0s - loss: 80.8174 - 30ms/epoch - 1ms/step
Epoch 91/100
23/23 - 0s - loss: 80.4285 - 28ms/epoch - 1ms/step
Epoch 92/100
23/23 - 0s - loss: 79.2975 - 26ms/epoch - 1ms/step
Epoch 93/100
23/23 - 0s - loss: 78.6154 - 29ms/epoch - 1ms/step
Epoch 94/100
23/23 - 0s - loss: 78.5779 - 30ms/epoch - 1ms/step
Epoch 95/100
23/23 - 0s - loss: 77.7412 - 27ms/epoch - 1ms/step
Epoch 96/100
23/23 - 0s - loss: 77.1016 - 28ms/epoch - 1ms/step
Epoch 97/100
23/23 - 0s - loss: 76.3721 - 31ms/epoch - 1ms/step
Epoch 98/100
23/23 - 0s - loss: 76.3490 - 27ms/epoch - 1ms/step
Epoch 99/100
23/23 - 0s - loss: 75.0419 - 29ms/epoch - 1ms/step
Epoch 100/100
23/23 - 0s - loss: 74.4868 - 31ms/epoch - 1ms/step

## Evaluation
Finally, we evaluate the model. To do this we use the mean squared error.

In [14]:
from sklearn.metrics import mean_squared_error
loss_value = R_model.evaluate(X_test, y_test)
y_predicted = R_model.predict(X_test)
MSE = mean_squared_error(y_test, y_predicted)
std_dev = np.std(MSE)
mean = np.mean(MSE)

print("The mean was found to be:", mean)
print("The standard deviation was found to be:", std_dev)

10/10 [==============================] - 0s 1ms/step - loss: 89.7996
10/10 [==============================] - 0s 1ms/step
The mean was found to be: 89.79962462947333
The standard deviation was found to be: 0.0

We then determine the mean and standard deviation of the mean squared error for 50 iterations.

In [15]:
Sum_MSE = 50
MSE_List= []
for n in range(0, Sum_MSE):
    X_train, X_test, y_train, y_test = train_test_split(predictors,  target, test_size=0.3, random_state = 4)
    R_model.fit(X_train, y_train, epochs=100, verbose=0)
    MSE = R_model.evaluate(X_test, y_test, verbose=0)
    print("Mean Squared Error",str(n+1),":",MSE)
    y_predicted = R_model.predict(X_test)
    MSE = mean_squared_error(y_test, y_predicted)
    MSE_List.append(MSE)

MSE_List = np.array(MSE_List)
mean = np.mean(MSE_List)
std_dev = np.std(MSE_List)


print("The mean of the mean squared errors were determined to be:", mean)
print("The standard deviation of the mean squared errors were determined to be", std_dev)

Mean Squared Error 1 : 46.41619873046875
10/10 [==============================] - 0s 1ms/step
Mean Squared Error 2 : 41.357967376708984
10/10 [==============================] - 0s 915us/step
Mean Squared Error 3 : 38.301673889160156
10/10 [==============================] - 0s 996us/step
Mean Squared Error 4 : 37.01289749145508
10/10 [==============================] - 0s 1ms/step
Mean Squared Error 5 : 38.058448791503906
10/10 [==============================] - 0s 1ms/step
Mean Squared Error 6 : 36.23224639892578
10/10 [==============================] - 0s 974us/step
Mean Squared Error 7 : 36.42011260986328
10/10 [==============================] - 0s 997us/step
Mean Squared Error 8 : 36.61741638183594
10/10 [==============================] - 0s 1ms/step
Mean Squared Error 9 : 36.385555267333984
10/10 [==============================] - 0s 1ms/step
Mean Squared Error 10 : 36.15361404418945
10/10 [==============================] - 0s 2ms/step
Mean Squared Error 11 : 35.175514221191406
10/10 [==============================] - 0s 996us/step
Mean Squared Error 12 : 35.18447494506836
10/10 [==============================] - 0s 994us/step
Mean Squared Error 13 : 34.51174545288086
10/10 [==============================] - 0s 2ms/step
Mean Squared Error 14 : 34.20134735107422
10/10 [==============================] - 0s 2ms/step
Mean Squared Error 15 : 34.192176818847656
10/10 [==============================] - 0s 1ms/step
Mean Squared Error 16 : 33.443580627441406
10/10 [==============================] - 0s 1ms/step
Mean Squared Error 17 : 34.0623779296875
10/10 [==============================] - 0s 886us/step
Mean Squared Error 18 : 34.60546112060547
10/10 [==============================] - 0s 1ms/step
Mean Squared Error 19 : 33.59579849243164
10/10 [==============================] - 0s 1ms/step
Mean Squared Error 20 : 34.225650787353516
10/10 [==============================] - 0s 1ms/step
Mean Squared Error 21 : 33.31134796142578
10/10 [==============================] - 0s 1ms/step
Mean Squared Error 22 : 33.2425651550293
10/10 [==============================] - 0s 2ms/step
Mean Squared Error 23 : 33.184181213378906
10/10 [==============================] - 0s 1000us/step
Mean Squared Error 24 : 33.277347564697266
10/10 [==============================] - 0s 885us/step
Mean Squared Error 25 : 32.641082763671875
10/10 [==============================] - 0s 1ms/step
Mean Squared Error 26 : 32.35238265991211
10/10 [==============================] - 0s 2ms/step
Mean Squared Error 27 : 32.391357421875
10/10 [==============================] - 0s 1ms/step
Mean Squared Error 28 : 32.571537017822266
10/10 [==============================] - 0s 1ms/step
Mean Squared Error 29 : 32.997562408447266
10/10 [==============================] - 0s 1ms/step
Mean Squared Error 30 : 32.63310241699219
10/10 [==============================] - 0s 1ms/step
Mean Squared Error 31 : 32.710052490234375
10/10 [==============================] - 0s 998us/step
Mean Squared Error 32 : 32.52362060546875
10/10 [==============================] - 0s 1ms/step
Mean Squared Error 33 : 32.92824172973633
10/10 [==============================] - 0s 1ms/step
Mean Squared Error 34 : 34.05227279663086
10/10 [==============================] - 0s 1ms/step
Mean Squared Error 35 : 33.36085510253906
10/10 [==============================] - 0s 1ms/step
Mean Squared Error 36 : 32.67910385131836
10/10 [==============================] - 0s 1ms/step
Mean Squared Error 37 : 32.9924430847168
10/10 [==============================] - 0s 1ms/step
Mean Squared Error 38 : 33.67095947265625
10/10 [==============================] - 0s 1ms/step
Mean Squared Error 39 : 34.1177864074707
10/10 [==============================] - 0s 1ms/step
Mean Squared Error 40 : 32.75886154174805
10/10 [==============================] - 0s 967us/step
Mean Squared Error 41 : 32.97370910644531
10/10 [==============================] - 0s 1ms/step
Mean Squared Error 42 : 32.8688850402832
10/10 [==============================] - 0s 1ms/step
Mean Squared Error 43 : 32.54325485229492
10/10 [==============================] - 0s 1ms/step
Mean Squared Error 44 : 33.59083557128906
10/10 [==============================] - 0s 1ms/step
Mean Squared Error 45 : 33.52772903442383
10/10 [==============================] - 0s 933us/step
Mean Squared Error 46 : 32.81718826293945
10/10 [==============================] - 0s 1ms/step
Mean Squared Error 47 : 32.96095275878906
10/10 [==============================] - 0s 2ms/step
Mean Squared Error 48 : 32.90230178833008
10/10 [==============================] - 0s 1ms/step
Mean Squared Error 49 : 34.00300979614258
10/10 [==============================] - 0s 1ms/step
Mean Squared Error 50 : 33.17214584350586
10/10 [==============================] - 0s 1ms/step
The mean of the mean squared errors were determined to be: 34.35821932225436
The standard deviation of the mean squared errors were determined to be 2.4952580620360716

## Conclusion
The mean in part D was lower than that of part B and C and the standard deviation was significantly lower than either of the previous parts indicating a greater precision and accuracy. This indicates that the greater the number of ephocs and hidden layers, the more accuate the model.